CREATE TABLE IF NOT EXISTS coingecko.daily_coin_info (
    _ts timestamptz NOT NULL,
    id VARCHAR(255) NOT NULL,
    symbol VARCHAR(255) NOT NULL, 
    name VARCHAR(255) NOT NULL, 
    image VARCHAR(500) NOT NULL, 
    current_price NUMERIC, 
    market_cap NUMERIC,
    market_cap_rank SMALLINT, 
    volume_rank SMALLINT, 
    rank_prop NUMERIC, 
    vol_cap_ratio NUMERIC,
    fully_diluted_valuation NUMERIC, 
    total_volume NUMERIC,
    high_24h NUMERIC, 
    low_24h NUMERIC, 
    price_change_24h NUMERIC,
    price_change_percentage_24h NUMERIC, 
    market_cap_change_24h NUMERIC,
    market_cap_change_percentage_24h NUMERIC, 
    circulating_supply NUMERIC,
    total_supply NUMERIC, 
    max_supply NUMERIC, 
    ath NUMERIC, 
    ath_change_percentage NUMERIC,
    ath_date timestamptz, 
    atl NUMERIC, 
    atl_change_percentage NUMERIC, 
    atl_date timestamptz, 
    roi JSON,
    last_updated timestamptz, 
    PRIMARY KEY (_ts, id)
);